name: Read Issue with Specific Tag and Update JSON

on:
  issues:
    types: [opened, labeled]

jobs:
  read_issue:
    if: github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'add/edit')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python .github/scripts/issue_add.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ env.GH_TOKEN }}@github.com/${{ github.repository }}
        git status
        git add .
        git commit -m "Update JSON file"
        git push origin HEAD:main
