name: Read Issue with Specific Tag and Update JSON

on:
  issues:
    types: [opened, labeled]

jobs:
  read_issue:
    if: github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'add/edit')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python .github/scripts/issue_add.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: "Update JSON file"
        branch: update-json-file
        title: "Update JSON file"
        body: "This PR updates the JSON file with the latest data."
        base: main

    - name: Close GitHub Issue
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python update_json.py -i ${{ github.event.issue.number }}
